spring.application.name=backend-api

# Koneksi ke MySQL (db_kos)
spring.datasource.url=jdbc:mysql://localhost:3306/db_kos
spring.datasource.username=root
spring.datasource.password=

# Spring Boot akan otomatis bikin tabel kalo belum ada
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
