spring.application.name=backend-api

# Koneksi ke MySQL (db_kos)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_kos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Spring Boot akan otomatis bikin tabel kalo belum ada
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
