/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1e",
        "primary-fixed-dim": "#c3c0ff",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#dad7ff",
        "error-container": "#ffdad6",
        "secondary": "#006b5f",
        "tertiary-container": "#5551c2",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed-variant": "#005048",
        "surface-bright": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#c7c4d8",
        "outline": "#777587",
        "surface": "#f7f9fb",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed": "#71f8e4",
        "on-secondary-fixed": "#00201c",
        "on-secondary-container": "#006f64",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "secondary-container": "#6df5e1",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#dbd7ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e2dfff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#4fdbc8",
        "on-surface-variant": "#464555",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#c3c0ff",
        "surface-container": "#eceef0",
        "on-tertiary-fixed-variant": "#3b35a7",
        "tertiary": "#3d37a9",
        "background": "#f7f9fb",
        "primary-container": "#4f46e5",
        "tertiary-fixed-dim": "#c3c0ff",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2dfff",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary": "#ffffff",
        "primary": "#3525cd",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#0f0069"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
